spring.application.name=Welcome-API

server.port=8081

; eureka.client.register-with-eureka=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*


spring.boot.admin.client.url=http://localhost:1111

#config server

spring.config.import=configserver:http://localhost:8080

#name  of file present in the github repo of config
spring.cloud.config.name=welcome