
spring.application.name=SpringBootProject06
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.show-sql= true
#
#spring.jpa.hibernate.ddl-auto=update


# Enable the H2 console interface
spring.h2.console.enabled=true

# Connect to an in-memory database named "testdb"
spring.datasource.url=jdbc:h2:mem:mydatabase
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
